### ISSUE TITLE
Symfony 5.4.7 from master branch instead of 6.0

### ISSUE THREAD

**Issue by aruku** [bitnami/bitnami-docker-symfony#77] opened 2022-04-14 09:59 UTC
### Name and Version

bitnami/symfony:6.0.7-debian-10-r7

### What steps will reproduce the bug?

Follow TL;DR instructions

### What is the expected behavior?

Get SF 6.0.7

### What do you see instead?

SF 5.4.7

### Additional information

Am I missing something?

**Comment by carrodher** [comment] 2022-04-17 00:20
Check the downloaded docker-compose, you should be downloading the one present at https://github.com/bitnami/bitnami-docker-symfony/blob/master/docker-compose.yml which is using Symfony 6.0.7

**Comment by aruku** [comment] 2022-04-17 15:52
> Check the downloaded docker-compose, you should be downloading the one present at https://github.com/bitnami/bitnami-docker-symfony/blob/master/docker-compose.yml which is using Symfony 6.0.7

Yep, that is what I used because that is what curl downloaded.

**Comment by carrodher** [comment] 2022-04-18 07:15
I just reproduced the issue and created an internal task to investigate and fix the issue.

I'm adding the `on-hold` label to this issue to avoid stale-bot from closing it. Due to the size of the team and other priorities, I can't provide an ETA for the issue to be fixed.

Thanks for reporting it!

**Comment by marcosbc** [comment] 2022-04-28 11:54
Hi @aruku, it seems this issue was fixed by itself. I just took [the following `docker-compose.yml` file](https://raw.githubusercontent.com/bitnami/bitnami-docker-symfony/master/docker-compose.yml) and it included 6.x:
![Screen Shot 2022-04-28 at 13 52 04](https://user-images.githubusercontent.com/5102866/165746393-94210bcb-aa85-45c6-a082-6653ea8daba5.png)

So I'm going to close this issue.

**Closed by marcosbc** 2022-04-28 11:54 UTC
Labels: on-hold
